// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI2020.DAL.Models
{
    public partial class Admin
    {
        public int Uid { get; set; }
        public string StrName { get; set; }
        public string StrEmail { get; set; }
        public string StrPassword { get; set; }
        public byte? IntAccess { get; set; }
    }
}