// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI2020.DAL.Models
{
    public partial class Site
    {
        public int IntSiteId { get; set; }
        public string StrName { get; set; }
        public string StrCoordinator { get; set; }
        public string StrAddress { get; set; }
        public string StrCity { get; set; }
        public byte? IntProvince { get; set; }
        public string StrPostal { get; set; }
        public string StrPhone { get; set; }
        public string StrFax { get; set; }
        public string StrEmail { get; set; }
        public string StrQ6 { get; set; }
        public string StrQ7 { get; set; }
        public string StrQ8 { get; set; }
        public string StrQ9 { get; set; }
        public string StrQ10 { get; set; }
        public string StrQ11 { get; set; }
        public string StrComments { get; set; }
        public DateTime? DtmCreated { get; set; }
        public string StrQ6french { get; set; }
        public string StrQ7french { get; set; }
        public string StrQ8french { get; set; }
        public string StrQ9french { get; set; }
        public string StrQ10french { get; set; }
        public string StrQ11french { get; set; }
    }
}