// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI2020.DAL.Models
{
    public partial class TeacherParticipation
    {
        public int IntTeacherId { get; set; }
        public short? Question1 { get; set; }
        public short? Question2 { get; set; }
        public short? Question3 { get; set; }
        public short? Question4 { get; set; }
        public byte? Question5 { get; set; }
        public byte? Question6 { get; set; }
        public byte? Question7Yh { get; set; }
        public byte? Question7Ynh { get; set; }
        public byte? Question7Nnh { get; set; }
        public byte? Question7Nnone { get; set; }
        public byte? Question7Ntime { get; set; }
        public byte? Question7Nfamiliar { get; set; }
        public byte? Question7Other { get; set; }
        public string Question7OtherText { get; set; }
        public int? StudentsInClass { get; set; }
        public DateTime? DtmCreated { get; set; }
        public string StrLanguageCompleted { get; set; }
    }
}