// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI2020.DAL.Models
{
    public partial class Teacher
    {
        public int IntTeacherId { get; set; }
        public int IntSchoolId { get; set; }
        public string StrName { get; set; }
        public string StrEmail { get; set; }
        public string StrPassword { get; set; }
        public string StrPhone { get; set; }
        public string StrFax { get; set; }
        public byte? IntSex { get; set; }
        public byte? IntAge { get; set; }
        public short? IntQ5a { get; set; }
        public short? IntQ5b { get; set; }
        public short? IntQ5c { get; set; }
        public short? IntQ5d { get; set; }
        public byte? IntQ6a { get; set; }
        public byte? IntQ6b { get; set; }
        public byte? IntQ6c { get; set; }
        public byte? IntQ6d { get; set; }
        public byte? IntQ6e { get; set; }
        public byte? IntQ6f { get; set; }
        public byte? IntQ6g { get; set; }
        public byte? IntQ6h { get; set; }
        public byte? IntQ6i { get; set; }
        public byte? IntQ6j { get; set; }
        public byte? IntQ6k { get; set; }
        public DateTime? DtmCreated { get; set; }
    }
}