// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI2020.DAL.Models
{
    public partial class TeacherTrainingFeedback
    {
        public int IntTeacherId { get; set; }
        public short? Question1a { get; set; }
        public short? Question1b { get; set; }
        public short? Question1c { get; set; }
        public short? IntQ2 { get; set; }
        public byte? IntQ3a { get; set; }
        public int? IntQ3b { get; set; }
        public int? IntQ3c { get; set; }
        public int? IntQ3d { get; set; }
        public int? IntQ3e { get; set; }
        public int? IntQ3f { get; set; }
        public int? IntQ3g { get; set; }
        public int? IntQ3h { get; set; }
        public string StrQ3other { get; set; }
        public byte? IntQ4a { get; set; }
        public byte? IntQ4b { get; set; }
        public byte? IntQ4c { get; set; }
        public byte? IntQ4d { get; set; }
        public byte? IntQ5a { get; set; }
        public byte? IntQ5b { get; set; }
        public byte? IntQ5c { get; set; }
        public byte? IntQ5d { get; set; }
        public int? IntQ6 { get; set; }
        public string StrMostBeneficial { get; set; }
        public string StrCommentseEdi { get; set; }
        public DateTime? DtmCreated { get; set; }
        public string StrLanguageCompleted { get; set; }
    }
}