// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI2020.DAL.Models
{
    public partial class TeacherClass
    {
        public int IntClassId { get; set; }
        public int? IntTeacherId { get; set; }
        public byte? IntLanguage { get; set; }
        public short? IntMonths { get; set; }
        public string StrComments { get; set; }
        public DateTime? DtmCreated { get; set; }
    }
}