// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI2020.DAL.Models
{
    public partial class School
    {
        public int IntSchoolId { get; set; }
        public int? IntSiteId { get; set; }
        public string StrName { get; set; }
        public string StrPrincipal { get; set; }
        public string StrAddress { get; set; }
        public string StrCity { get; set; }
        public byte? IntProvince { get; set; }
        public string StrPostal { get; set; }
        public string StrPhone { get; set; }
        public string StrFax { get; set; }
        public string StrEmail { get; set; }
        public string StrComments { get; set; }
        public bool? IntElp { get; set; }
        public DateTime? DtmCreated { get; set; }
    }
}